// <auto-generated />
namespace HeuristicAnalysis.Infrastructure.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_Images : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Images));
        
        string IMigrationMetadata.Id
        {
            get { return "201810312145340_added_Images"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
