// <auto-generated />
namespace HeuristicAnalysis.Infrastructure.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedAppTypeAndResolvedToAnswer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedAppTypeAndResolvedToAnswer));
        
        string IMigrationMetadata.Id
        {
            get { return "201908281826589_AddedAppTypeAndResolvedToAnswer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
